#!/bin/sh

set -euo pipefail
set -x 

id -a 

export HOME=/tmp

cat /etc/*release
python --version

pip freeze

pushd /tmp
curl -L https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py --user
cd .local/bin
./pip install --user awscli
./aws sts get-caller-identity --output text --query 'Account'

# Initialization - load function handler
source $LAMBDA_TASK_ROOT/"$(echo $_HANDLER | cut -d. -f1).sh"

# Processing
while true
do
  HEADERS="$(mktemp)"
  # Get an event
  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")
  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

  # Execute the handler function from the script
  RESPONSE=$(./aws sts get-caller-identity --output text --query 'Account')

  # Send the response
  curl -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response"  -d "$RESPONSE"
done
